---
title: CASTOR Software Days
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://castor-software-days-2019.github.io/
baseurl: "/"
email: payberah@kth.se
description: ''
organization:
- name: Benoit Baudry
  pic: benoit
  position: Professor in Software Technology at KTH
  social:
  - title: globe
    url: https://softwarediversity.eu
  - title: envelope
    url: mailto:baudry@kth.se
- name: Frédéric Loiret
  pic: frederic
  position: Senior researcher and cooperative R&D project manager at KTH
  social:
  - title: globe
    url: http://www.scanx.org/loiret/
  - title: envelope
    url: mailto:floiret@kth.se
- name: Amir H. Payberah
  pic: amir
  position: Assistant Professor in the Software and Computer Systems division at KTH
  social:
  - title: globe
    url: https://payberah.github.io/
  - title: envelope
    url: mailto:payberah@kth.se
- name: Musard Balliu
  pic: musard
  position: Assistant Professor in the Theoretical Computer Science division at KTH
  social:
  - title: globe
    url: https://www.csc.kth.se/~musard/
  - title: envelope
    url: mailto:musard@kth.se
- name: Cyrille Artho
  pic: cyrille
  position: Associate Professor in the Theoretical Computer Science division at KTH
  social:
  - title: globe
    url: https://people.kth.se/~artho/
  - title: envelope
    url: mailto:artho@kth.se
- name: Philipp Haller
  pic: philipp
  position: Associate professor of computer science in the Theoretical Computer Science
    division at KTH
  social:
  - title: globe
    url: http://www.csc.kth.se/~phaller/
  - title: envelope
    url: mailto:phaller@kth.se
- name: Maria Berthelius
  pic: maria
  position: Service coordinator at the school of Electrical Engineering and Computer
    Science at KTH
  social:
  - title: globe
    url: https://www.kth.se/profile/berthel
  - title: envelope
    url: mailto:berthel@kth.se
- name: Alexandra Leyton
  pic: alexandra
  position: Communication officer at the school of Electrical Engineering and Computer
    Science at KTH
  social:
  - title: globe
    url: https://www.kth.se/profile/aleyton
  - title: envelope
    url: mailto:aleyton@kth.se
- name: Oscar Luis Vera-Pérez
  pic: oscar
  position: PhD student at Inria
  social:
  - title: globe
    url: https://www.linkedin.com/in/oscar-luis-vera-p%C3%A9rez-608392125
  - title: envelope
    url: mailto:oscar.vera-perez@inria.fr
speakers:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
  - title: twitter
    url: 
  - title: facebook
    url: 
  - title: stack-overflow
    url: 
- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
  - title: twitter
    url: 
  - title: facebook
    url: 
  - title: linkedin
    url: 
- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
  - title: twitter
    url: 
  - title: facebook
    url: 
  - title: google-plus
    url: 
social:
- title: twitter
  url: https://twitter.com/CastorKth
- title: globe
  url: https://www.castor.kth.se
